### ISSUE TITLE
`sbt dependencyUpdates` finds updates that Scala Steward 0.8.1-207 does not

### ISSUE THREAD

**Issue by zzvara** [scala-steward-org/scala-steward#1876]
Scala Steward deployed with:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: scala-steward-job
  namespace: development
spec:
  chart:
    git: redacted
    path: "charts/scala-steward"
    ref: master
  releaseName: scala-steward-job
  values:
    scalaStewardArgs:
      - --workspace
      - /var/scala-steward/workspace
      - --repos-file
      - /opt/scala-steward/repos.md
      - --vcs-api-host
      - redacted
      - --git-ask-pass
      - /opt/scala-steward/password.sh
      - --scalafix-migrations
      - /opt/scala-steward/scalafix.conf
      - --do-not-fork
    additionalScalaStewardArgs:
      - --git-author-email
      - redacted
      - --vcs-type
      - bitbucket-server
      - --vcs-login
      - redacted
      - --cache-ttl
      - 0s
    additionalScalaStewardEnvs: {}
    repos: [
      redacted
    ]
    scalafixConfig: |
      disableDefaults = false
      migrations = []

    gitSecret: "redacted"
    existingGitSecretName: ""

    image:
      tag: 0.8.1-207-1bec1ac7-SNAPSHOT
      repository: fthomas/scala-steward
      pullPolicy: IfNotPresent

    schedule: "*/5 * * * *"
    concurrencyPolicy: "Forbid"

    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""

    resources: {}

    persistence:
      enabled: false
      className: "local"
      annotations: {}
      accessModes:
        - ReadWriteOnce
      size: 5Gi
```

The dependency updates not discovered are in a JFrog Artifactory 7 and behind authentication. The exact Scala Steward for the said dependency updates worked at around version 0.5~0.6, not sure. We upgraded the above Helm release directly to 0.8 and then these private dependencies are no longer detected. There are no errors, Scala Steward does not print the updates for several private repositories as `sbt dependencyUpdates` do.

I noticed that: "Scala Steward wouldn't exist without the great sbt-updates plugin which was used until version 0.6 to find dependency updates."

May the issue be that `sbt-updates` functionality is lost somewhere in 0.8?
