### ISSUE TITLE
Is scala steward still running

### ISSUE THREAD

**Issue by yanns** [scala-steward-org/scala-steward#2733]
I don't receive any updates anymore in open source libraries ([sangria](https://github.com/sangria-graphql/sangria) for example).
Is the bot still running? Do you need help?

**Comment by plokhotnyuk** [comment]
ICYMI: currently the scala-steward instance is maintained by VirtusLab: https://github.com/VirtusLab/scala-steward-repos

**Comment by plokhotnyuk** [comment]
Ups... Probably need to ask them for the service restart.

**Comment by yanns** [comment]
Can I help?

**Comment by fthomas** [comment]
Nobody from VirtusLab is watching this repo, so I would suggest asking that in https://github.com/VirtusLab/scala-steward-repos.

**Comment by yanns** [comment]
I don't see any way to interact with anyone on https://github.com/scala-steward-org/scala-steward/issues/2733#issuecomment-1278704305. There are no issues, nothing.

**Comment by yanns** [comment]
Trying to catch @tgodzik attention.

**Comment by tgodzik** [comment]
Looking into that, I assumed that it was setup correctly previously, but I think something might be off. There is not enough PRs on https://github.com/scala-steward

I wonder why no one reported anything :thinking:

**Comment by tgodzik** [comment]
Enabled issues in the repo! Looks like the steward job is getting a lot of timeouts from github, though I don't have a direct access to the azure job yet, looking into that.

**Comment by tgodzik** [comment]
Github is not happy, seems there is limit on ither creating or querying pull requests.
```
{"message":"You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#secondary-rate-limits"}
```

**Comment by tgodzik** [comment]
I restarted the container, let's see if the github issues were temporary or something we need to deal with.

**Comment by fthomas** [comment]
I've seen the secondary rate limit issue before in https://github.com/scala-steward-org/scala-steward/issues/2355 but that only happened when Scala Steward created a lot of PRs in a short time frame - usually when there was a new Scala or sbt release. But this was always temporary and Scala Steward was always able to create PRs on the next run.

**Comment by tgodzik** [comment]
Ok, the rerun managed to create a bunch of PRs but after a short while again 403. Might be related to the fact that we haven't run it for a while.

**Comment by tgodzik** [comment]
```
method: POST
status: 403 Forbidden
headers:
  access-control-allow-origin: *
  access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
  content-security-policy: default-src 'none'
  content-type: application/json; charset=utf-8
  date: Fri, 14 Oct 2022 13:06:09 GMT
  referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
  server: GitHub.com
  strict-transport-security: max-age=31536000; includeSubdomains; preload
  vary: Accept-Encoding, Accept, X-Requested-With
  x-accepted-oauth-scopes: 
  x-content-type-options: nosniff
  x-frame-options: deny
  x-github-media-type: github.v3
  x-github-request-id: 2140:7CD2:2437198:24BFB2E:63495EAF
  x-oauth-scopes: delete_repo, notifications, repo, workflow
  x-ratelimit-limit: 5000
  x-ratelimit-remaining: 4737
  x-ratelimit-reset: 1665753242
  x-ratelimit-resource: core
  x-ratelimit-used: 263
  x-xss-protection: 0
  ```

`x-ratelimit-remaining: 4737` seems to suggest we should be good, but it's rejecting the request anyway.
